### ISSUE TITLE
Error Compilation FreeImage/Ogre

### ISSUE THREAD

**Issue by Mvivant** [MTASZTAKI/ApertusVR#190]
I have a compilation error during CMAKE's generation

* branch 0.9.1
* Windows 10
* CMake 3.16.2
* Visual Studio 2017 Community 15.9.20

```
c:\projets\apertusvr\plugins\render\ogrerender\3rdparty\ogre\dependencies\src\freeimage\source\librawlite\internal\dcraw_common.cpp(4509): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'd:\agent\_work\8\s\src\vctools\compiler\utc\src\p2\main.c', line 187)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
```

**Comment by pkovacs86** [comment]
According to the documentation CMake version 3.13.2 or below is supported.
https://apertus.gitbook.io/vr/developers/developers-guide

BTW, you can download the pre-built version of the 0.9 branch
https://github.com/MTASZTAKI/ApertusVR/releases

Please let me know if you have any further question

**Comment by pkovacs86** [comment]
Meanwhile, I recognized that you would like to build the 0.9.1 branch.
Currently, only the 0.9 branch was released, as I mentioned.
Anyways, you can build the development branch (0.9.1) as well, but the cmake system of the 0.9.1 is not so strong, yet.

**Comment by Mvivant** [comment]
Ok, I just want to test the release of 3dRudder in ApertuVR 👍

**Comment by pkovacs86** [comment]
I see, then please use the 0.9.1 branch and CMake version 3.13.2 or below

**Comment by pkovacs86** [comment]
after cmake and build, just run:
c:\ApertusVR-build\bin\release>apeSampleLauncher.exe c:\ApertusVR\samples\controller\3dRudder\

**Comment by Mvivant** [comment]
I have the same error with cmake 3.13.2

**Comment by pkovacs86** [comment]
The current generator is Visual Studio 15 2017 Win64?

**Comment by Mvivant** [comment]
The C compiler identification is MSVC 19.16.27035.0

**Comment by pkovacs86** [comment]
Moreover, maybe you should delete cache in CMAKe or even delete the whole build folder

**Comment by Mvivant** [comment]
Yes I already delete the cmake build folder, before compiling

**Comment by pkovacs86** [comment]
"The C compiler identification is MSVC 19.16.27035.0"
It seems that the  current generator is NOT Visual Studio 15 2017

**Comment by pkovacs86** [comment]
My compiler version is 19.12.25835.0, but I guess it should work with 19.16.X

**Comment by Mvivant** [comment]
It works with "Visual Studio 15 2017 **win64**"
But can't launch  **apeSampleLauncher.exe**
```
apertusVR - Your open source AR/VR engine for science, education and industry
Build Target Platform: Windows 64
CoreConfigImpl: loading config files from C:\Projets\ApertusVR\samples\controller\3dRudder
An unexpected error while loading library: apeOgreRenderPlugin.dll error: 126
Get last error while loading library: apeOgreRenderPlugin.dll error : 126
ERROR: LN    61:         ape::PluginManagerImpl::CreatePlugins: Can not load plugin: apeOgreRenderPlugin
An unexpected error while loading library: apeOisUserInputPlugin.dll error: 126
Get last error while loading library: apeOisUserInputPlugin.dll error : 126
ERROR: LN    61:         ape::PluginManagerImpl::CreatePlugins: Can not load plugin: apeOisUserInputPlugin
An unexpected error while loading library: apeHelloWorldScenePlugin.dll error: 126
Get last error while loading library: apeHelloWorldScenePlugin.dll error : 126
ERROR: LN    61:         ape::PluginManagerImpl::CreatePlugins: Can not load plugin: apeHelloWorldScenePlugin
An unexpected error while loading library: apeViewPointManagerPlugin.dll error: 126
Get last error while loading library: apeViewPointManagerPlugin.dll error : 126
ERROR: LN    61:         ape::PluginManagerImpl::CreatePlugins: Can not load plugin: apeViewPointManagerPlugin
An unexpected error while loading library: ape3dRudderControllerPlugin.dll error: 126
Get last error while loading library: ape3dRudderControllerPlugin.dll error : 126
ERROR: LN    61:         ape::PluginManagerImpl::CreatePlugins: Can not load plugin: ape3dRudderControllerPlugin
```

**Comment by pkovacs86** [comment]
Did you build the generated solution file?
c:\ApertusVR-build\apertusVR.sln

**Comment by Mvivant** [comment]
Ok my bad I rebuild all and it's ok, thank you 👍

**Comment by pkovacs86** [comment]
Perfect, thank you :)
