### ISSUE TITLE
Math computational issues

### ISSUE THREAD

**Issue by akibaki97** [MTASZTAKI/ApertusVR#191]
The following lines contains equality tests with floating point numbers:
- apeVector3.h, ln. 137
- apeQuaternion.h, ln. 172
- apeMatrix3.h, ln. 101
- apeMatrix4.h, ln. 229-232, 240-243

Other issues:
- In apeQuaternion.h, ln. 175, the `Norm()` function returns the squared length of the quaternion which can be confusing. In ln. 180 the `normalise()` function works fine, but should be modified if the norm isssue is solved.
- In apeMatrix4.h, ln. 294-354, the inverse computation should test if the determinant equals to 0 (or small enough to treat as 0), and return a `bool` value, just like in the `Matrix3` case (apeMatrix3.h, ln. 190).
- In apeMatrix4.h, ln. 281-292, if the 3x3 submatrix known to be orthogonal (so the given `Matrix4` represents an affine transformation), it isn't necessary to perform a QR decomposition for obtaining the rotation matrix (even if it works fine). Should be enough to divide the columns with their norms, and store the norms in the scale `Vector3`.

**Comment by aklen** [comment]
I would implement an apeScalar struct like this one:
https://github.com/BabylonJS/Babylon.js/blob/1b1f35ea3325478de4a6482777a28976e9107de2/src/Maths/math.scalar.ts#L18
and fix the problems above by checking this:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Maths/math.vector.ts
