### ISSUE TITLE
Lobby

### ISSUE THREAD

**Issue by pkovacs86** [MTASZTAKI/ApertusVR#39]

**Comment by aklen** [comment]
Lobby pull requests:
cd72a0433dc5fd6ed243ad8e5948eb4536c59423
a88884af2c6d35c08983827bc4bb22bfcadf2f1b
2633d23129621cf743fbb12cc07adfe9d0568227

**Comment by hamoriakos** [comment]
Lobby pull requests:
cd72a0433dc5fd6ed243ad8e5948eb4536c59423
a88884af2c6d35c08983827bc4bb22bfcadf2f1b
2633d23129621cf743fbb12cc07adfe9d0568227
