### ISSUE TITLE
JSAPI refactor

### ISSUE THREAD

**Issue by pkovacs86** [MTASZTAKI/ApertusVR#43]
-  exclude binding.cpp
-  create the JS pairs of the singletons and ifaces
    e.g ApeSceneJSBindImpl, ApeSystemConfigJSBindImpl, and so on...
-  refactor the binded c++ classes filenames e.g ApeJSBindColor.h to ApeColorJSBingImpl.h and also create a source file if it is needed
-   the generated files and folders should go to the cmake out folder instead of next to the source

**Comment by hamoriakos** [comment]
Fixed in AHA-dev branch.
